
title: Welcome to Chloe-Ninefeldt's homepage!
description: This is my portfolio of some projects I have done during my time at SNHU.
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
